%{
#include <fstream>
using namespace std;
ofstream ssym("../tmp/cpp.sym");
ofstream sssm("../tmp/cpp.ssm");
ofstream sstr("../tmp/cpp.str");
ofstream i("../tmp/cpp.int");
ofstream n("../tmp/cpp.num");
ofstream h("../tmp/cpp.hex");
ofstream b("../tmp/cpp.bin");
int par=0;
%}
%option main
%%
^.*sym::.*\n	{ ssym<<yytext; }
^.*Sym::.*\n	{ sssm<<yytext; }
^.*Str::.*\n	{ sstr<<yytext; }
^.*Int::.*\n	{ i<<yytext; }
^.*Num::.*\n	{ n<<yytext; }
^.*Hex::.*\n	{ h<<yytext; }
^.*Bin::.*\n	{ b<<yytext; }
%%